### ISSUE TITLE
When updating the image version the container is not redeployed

### ISSUE THREAD

**Issue by sinaure** [yamatt/scaleway-serverless-container-deploy-action#2]
The container is not updated 

```
Run yamatt/scaleway-serverless-container-deploy-action@main
  with:
    container_id: 861546b0-d851-471c-87db-4b23b7f87256
    secret_key: ***
    registry_image_url: rg.fr-par.scw.cloud/funcscwynovmwg0m0ur/ynov-secure:v1.1.0
    region: fr-par
    api_version: v1beta1
  env:
    DOCKER_BUILDKIT: 1
    REGION: fr-par
    REGISTRY_URL: rg.fr-par.scw.cloud/funcscwynovmwg0m0ur
    CONTAINER_ID: 861546b0-d851-471c-87db-4b23b7f87256
```
{"message":"Not found"}
